----
 Title: Course Project
 Author: JSAMSON 
----   


### Loading and preprocessing the data
```{r loading, echo=FALSE}
wtemp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", wtemp, mode="wb")
unzip(wtemp, "activity.csv")
Newactivity <- read.table("activity.csv", sep=",", header=T)
head(Newactivity)

activityCopy <- Newactivity

str(Newactivity$date)
Newactivity$Date <- as.Date(Newactivity$date, "%Y-%m-%d")
Newactivity$interval <- as.factor(Newactivity$interval)

l <- levels(Newactivity$interval)
```

### 1) What is mean total number of steps taken per day?

```{r totalmean, echo=FALSE}
totalSteps <- tapply(Newactivity$steps, Newactivity$date, sum, na.rm=T)
avgSteps <- tapply(Newactivity$steps, Newactivity$date, mean, na.rm=T)
par(mfrow=c(2,1))
hist(totalSteps, breaks=10, col="red", main="Distribution of the total Number of steps each day", xlab="Average Total Number of Steps")
hist(as.vector(avgSteps), breaks=10, col="blue", main="Distribution of the Average Number of steps each day", xlab="Average Number of Steps")

steps_by_day <- aggregate(steps ~ date, Newactivity, sum)

head(steps_by_day)
rmean <- mean(steps_by_day$steps)
rmean

rmedian <- median(steps_by_day$steps)
rmedian
```

### 2) What is the average daily activity pattern?

```{r dailyaverage, echo=FALSE}
steps_by_interval <- aggregate(steps ~ interval, Newactivity, mean)
plot(steps_by_interval$interval,steps_by_interval$steps, type="l", xlab="Interval", ylab="Number of Steps",main="Average Number of Steps per Day by Interval")

max_interval <- steps_by_interval[which.max(steps_by_interval$steps),1]
max_interval

```

### The interval with most steps is

### 3) Imputing missing values

```{r missing, echo=FALSE}

NATotal <- sum(!complete.cases(Newactivity))
NATotal

#### Total Number of Missing values are 2304

missing <- is.na(Newactivity)
activityCopy$steps[is.na(activityCopy$steps)] <- tapply(activityCopy$steps, activityCopy$interval, mean, na.rm = TRUE)
totStepsImp <- tapply(activityCopy$steps, activityCopy$date, sum)

summary(totalSteps)
summary(totStepsImp)

par(mfrow=c(2,1))
hist(totalSteps, col="red", xlab="Average Total Number of Steps Before Imputing", main="", breaks=10)
title("Distribution of the total Number of steps\n each day Before and After Imputing")
hist(totStepsImp, col="cyan", main="", xlab="Average Total Number of Steps After Imputing", breaks=10)
```

### 4) Are there differences in activity patterns between weekdays and weekends?

```{r difference, echo=FALSE}

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
activityCopy$dow = as.factor(ifelse(is.element(weekdays(as.Date(activityCopy$date)),weekdays), "Weekday", "Weekend"))
StepsTotalUnion <- aggregate(steps ~ interval + dow, activityCopy, mean)
library(lattice)
xyplot(StepsTotalUnion$steps ~ StepsTotalUnion$interval|StepsTotalUnion$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Steps",layout=c(1,2), type="l")

```
